/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int INTEGER = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\31\1\3\1\2\1\0\1\3\1\1\16\31\4\0\1\3\1\34"+
    "\1\40\1\27\1\30\3\0\1\33\1\33\1\33\1\33\1\0\1\36"+
    "\1\33\1\26\12\32\1\0\1\33\1\34\1\35\1\34\2\0\32\30"+
    "\1\0\1\41\2\0\1\30\1\0\1\17\1\13\1\24\1\10\1\15"+
    "\1\5\1\23\1\25\1\4\2\30\1\14\1\37\1\6\1\11\1\22"+
    "\1\30\1\16\1\20\1\7\1\12\1\21\4\30\1\33\1\0\1\33"+
    "\1\0\41\31\2\0\4\30\4\0\1\30\2\0\1\31\7\0\1\30"+
    "\4\0\1\30\5\0\27\30\1\0\37\30\1\0\u01ca\30\4\0\14\30"+
    "\16\0\5\30\7\0\1\30\1\0\1\30\21\0\160\31\5\30\1\0"+
    "\2\30\2\0\4\30\1\0\1\30\6\0\1\30\1\0\3\30\1\0"+
    "\1\30\1\0\24\30\1\0\123\30\1\0\213\30\1\0\5\31\2\0"+
    "\246\30\1\0\46\30\2\0\1\30\7\0\47\30\7\0\1\30\1\0"+
    "\55\31\1\0\1\31\1\0\2\31\1\0\2\31\1\0\1\31\10\0"+
    "\33\30\5\0\3\30\15\0\6\31\5\0\1\30\4\0\13\31\1\0"+
    "\1\31\3\0\53\30\37\31\4\0\2\30\1\31\143\30\1\0\1\30"+
    "\10\31\1\0\6\31\2\30\2\31\1\0\4\31\2\30\12\31\3\30"+
    "\2\0\1\30\17\0\1\31\1\30\1\31\36\30\33\31\2\0\131\30"+
    "\13\31\1\30\16\0\12\31\41\30\11\31\2\30\4\0\1\30\5\0"+
    "\26\30\4\31\1\30\11\31\1\30\3\31\1\30\5\31\22\0\31\30"+
    "\3\31\4\0\13\30\65\0\25\30\1\0\10\30\26\0\60\31\66\30"+
    "\3\31\1\30\22\31\1\30\7\31\12\30\2\31\2\0\12\31\1\0"+
    "\20\30\3\31\1\0\10\30\2\0\2\30\2\0\26\30\1\0\7\30"+
    "\1\0\1\30\3\0\4\30\2\0\1\31\1\30\7\31\2\0\2\31"+
    "\2\0\3\31\1\30\10\0\1\31\4\0\2\30\1\0\3\30\2\31"+
    "\2\0\12\31\4\30\7\0\2\30\4\0\3\31\1\0\6\30\4\0"+
    "\2\30\2\0\26\30\1\0\7\30\1\0\2\30\1\0\2\30\1\0"+
    "\2\30\2\0\1\31\1\0\5\31\4\0\2\31\2\0\3\31\3\0"+
    "\1\31\7\0\4\30\1\0\1\30\7\0\14\31\3\30\1\31\13\0"+
    "\3\31\1\0\11\30\1\0\3\30\1\0\26\30\1\0\7\30\1\0"+
    "\2\30\1\0\5\30\2\0\1\31\1\30\10\31\1\0\3\31\1\0"+
    "\3\31\2\0\1\30\17\0\2\30\2\31\2\0\12\31\1\0\1\30"+
    "\7\0\1\30\6\31\1\0\3\31\1\0\10\30\2\0\2\30\2\0"+
    "\26\30\1\0\7\30\1\0\2\30\1\0\5\30\2\0\1\31\1\30"+
    "\7\31\2\0\2\31\2\0\3\31\10\0\2\31\4\0\2\30\1\0"+
    "\3\30\2\31\2\0\12\31\1\0\1\30\20\0\1\31\1\30\1\0"+
    "\6\30\3\0\3\30\1\0\4\30\3\0\2\30\1\0\1\30\1\0"+
    "\2\30\3\0\2\30\3\0\3\30\3\0\14\30\4\0\5\31\3\0"+
    "\3\31\1\0\4\31\2\0\1\30\6\0\1\31\16\0\12\31\11\0"+
    "\1\30\6\0\4\31\1\0\10\30\1\0\3\30\1\0\27\30\1\0"+
    "\20\30\3\0\1\30\7\31\1\0\3\31\1\0\4\31\7\0\2\31"+
    "\1\0\3\30\5\0\2\30\2\31\2\0\12\31\20\0\1\30\3\31"+
    "\1\0\10\30\1\0\3\30\1\0\27\30\1\0\12\30\1\0\5\30"+
    "\2\0\1\31\1\30\7\31\1\0\3\31\1\0\4\31\7\0\2\31"+
    "\7\0\1\30\1\0\2\30\2\31\2\0\12\31\1\0\2\30\15\0"+
    "\4\31\1\0\10\30\1\0\3\30\1\0\51\30\2\31\1\30\7\31"+
    "\1\0\3\31\1\0\4\31\1\30\5\0\3\30\1\31\7\0\3\30"+
    "\2\31\2\0\12\31\12\0\6\30\2\0\2\31\1\0\22\30\3\0"+
    "\30\30\1\0\11\30\1\0\1\30\2\0\7\30\3\0\1\31\4\0"+
    "\6\31\1\0\1\31\1\0\10\31\6\0\12\31\2\0\2\31\15\0"+
    "\60\30\1\31\2\30\7\31\4\0\10\30\10\31\1\0\12\31\47\0"+
    "\2\30\1\0\1\30\2\0\2\30\1\0\1\30\2\0\1\30\6\0"+
    "\4\30\1\0\7\30\1\0\3\30\1\0\1\30\1\0\1\30\2\0"+
    "\2\30\1\0\4\30\1\31\2\30\6\31\1\0\2\31\1\30\2\0"+
    "\5\30\1\0\1\30\1\0\6\31\2\0\12\31\2\0\4\30\40\0"+
    "\1\30\27\0\2\31\6\0\12\31\13\0\1\31\1\0\1\31\1\0"+
    "\1\31\4\0\2\31\10\30\1\0\44\30\4\0\24\31\1\0\2\31"+
    "\5\30\13\31\1\0\44\31\11\0\1\31\71\0\53\30\24\31\1\30"+
    "\12\31\6\0\6\30\4\31\4\30\3\31\1\30\3\31\2\30\7\31"+
    "\3\30\4\31\15\30\14\31\1\30\17\31\2\0\46\30\1\0\1\30"+
    "\5\0\1\30\2\0\53\30\1\0\u014d\30\1\0\4\30\2\0\7\30"+
    "\1\0\1\30\1\0\4\30\2\0\51\30\1\0\4\30\2\0\41\30"+
    "\1\0\4\30\2\0\7\30\1\0\1\30\1\0\4\30\2\0\17\30"+
    "\1\0\71\30\1\0\4\30\2\0\103\30\2\0\3\31\40\0\20\30"+
    "\20\0\126\30\2\0\6\30\3\0\u026c\30\2\0\21\30\1\0\32\30"+
    "\5\0\113\30\3\0\13\30\7\0\15\30\1\0\4\30\3\31\13\0"+
    "\22\30\3\31\13\0\22\30\2\31\14\0\15\30\1\0\3\30\1\0"+
    "\2\31\14\0\64\30\40\31\3\0\1\30\3\0\2\30\1\31\2\0"+
    "\12\31\41\0\4\31\1\0\12\31\6\0\130\30\10\0\5\30\2\31"+
    "\42\30\1\31\1\30\5\0\106\30\12\0\37\30\1\0\14\31\4\0"+
    "\14\31\12\0\12\31\36\30\2\0\5\30\13\0\54\30\4\0\32\30"+
    "\6\0\12\31\46\0\27\30\5\31\4\0\65\30\12\31\1\0\35\31"+
    "\2\0\13\31\6\0\12\31\15\0\1\30\10\0\16\31\102\0\5\31"+
    "\57\30\21\31\7\30\4\0\12\31\21\0\11\31\14\0\3\31\36\30"+
    "\15\31\2\30\12\31\54\30\16\31\14\0\44\30\24\31\10\0\12\31"+
    "\3\0\3\30\12\31\44\30\2\0\11\30\107\0\3\31\1\0\25\31"+
    "\4\30\1\31\4\30\3\31\2\30\3\31\6\0\300\30\72\31\1\0"+
    "\5\31\u0116\30\2\0\6\30\2\0\46\30\2\0\6\30\2\0\10\30"+
    "\1\0\1\30\1\0\1\30\1\0\1\30\1\0\37\30\2\0\65\30"+
    "\1\0\7\30\1\0\1\30\3\0\3\30\1\0\7\30\3\0\4\30"+
    "\2\0\6\30\4\0\15\30\5\0\3\30\1\0\7\30\16\0\5\31"+
    "\32\0\5\31\20\0\2\30\23\0\1\30\13\0\5\31\1\0\12\31"+
    "\1\0\1\30\15\0\1\30\20\0\15\30\3\0\40\30\20\0\15\31"+
    "\4\0\1\31\3\0\14\31\21\0\1\30\4\0\1\30\2\0\12\30"+
    "\1\0\1\30\3\0\5\30\6\0\1\30\1\0\1\30\1\0\1\30"+
    "\1\0\4\30\1\0\13\30\2\0\4\30\5\0\5\30\4\0\1\30"+
    "\21\0\51\30\u0a77\0\57\30\1\0\57\30\1\0\205\30\6\0\4\30"+
    "\3\31\2\30\14\0\46\30\1\0\1\30\5\0\1\30\2\0\70\30"+
    "\7\0\1\30\17\0\1\31\27\30\11\0\7\30\1\0\7\30\1\0"+
    "\7\30\1\0\7\30\1\0\7\30\1\0\7\30\1\0\7\30\1\0"+
    "\7\30\1\0\40\31\57\0\1\30\u01d5\0\3\30\31\0\11\30\6\31"+
    "\1\0\5\30\2\0\5\30\4\0\126\30\2\0\2\31\2\0\3\30"+
    "\1\0\132\30\1\0\4\30\5\0\52\30\2\0\136\30\21\0\33\30"+
    "\65\0\20\30\u0200\0\u19b6\30\112\0\u51eb\30\25\0\u048d\30\103\0\56\30"+
    "\2\0\u010d\30\3\0\20\30\12\31\2\30\24\0\57\30\1\31\4\0"+
    "\12\31\1\0\37\30\2\31\120\30\2\31\45\0\11\30\2\0\147\30"+
    "\2\0\44\30\1\0\10\30\77\0\13\30\1\31\3\30\1\31\4\30"+
    "\1\31\27\30\5\31\20\0\1\30\7\0\64\30\14\0\2\31\62\30"+
    "\22\31\12\0\12\31\6\0\22\31\6\30\3\0\1\30\1\0\1\30"+
    "\2\0\12\31\34\30\10\31\2\0\27\30\15\31\14\0\35\30\3\0"+
    "\4\31\57\30\16\31\16\0\1\30\12\31\6\0\5\30\1\31\12\30"+
    "\12\31\5\30\1\0\51\30\16\31\11\0\3\30\1\31\10\30\2\31"+
    "\2\0\12\31\6\0\27\30\3\0\1\30\3\31\62\30\1\31\1\30"+
    "\3\31\2\30\2\31\5\30\2\31\1\30\1\31\1\30\30\0\3\30"+
    "\2\0\13\30\5\31\2\0\3\30\2\31\12\0\6\30\2\0\6\30"+
    "\2\0\6\30\11\0\7\30\1\0\7\30\1\0\53\30\1\0\12\30"+
    "\12\0\163\30\10\31\1\0\2\31\2\0\12\31\6\0\u2ba4\30\14\0"+
    "\27\30\4\0\61\30\u2104\0\u016e\30\2\0\152\30\46\0\7\30\14\0"+
    "\5\30\5\0\1\30\1\31\12\30\1\0\15\30\1\0\5\30\1\0"+
    "\1\30\1\0\2\30\1\0\2\30\1\0\154\30\41\0\u016b\30\22\0"+
    "\100\30\2\0\66\30\50\0\15\30\3\0\20\31\20\0\20\31\3\0"+
    "\2\30\30\0\3\30\31\0\1\30\6\0\5\30\1\0\207\30\2\0"+
    "\1\31\4\0\1\30\13\0\12\31\7\0\32\30\4\0\1\30\1\0"+
    "\32\30\13\0\131\30\3\0\6\30\2\0\6\30\2\0\6\30\2\0"+
    "\3\30\3\0\2\30\3\0\2\30\22\0\3\31\4\0\14\30\1\0"+
    "\32\30\1\0\23\30\1\0\2\30\1\0\17\30\2\0\16\30\42\0"+
    "\173\30\105\0\65\30\210\0\1\31\202\0\35\30\3\0\61\30\17\0"+
    "\1\31\37\0\40\30\15\0\36\30\5\0\46\30\5\31\5\0\36\30"+
    "\2\0\44\30\4\0\10\30\1\0\5\30\52\0\236\30\2\0\12\31"+
    "\6\0\44\30\4\0\44\30\4\0\50\30\10\0\64\30\234\0\u0137\30"+
    "\11\0\26\30\12\0\10\30\230\0\6\30\2\0\1\30\1\0\54\30"+
    "\1\0\2\30\3\0\1\30\2\0\27\30\12\0\27\30\11\0\37\30"+
    "\101\0\23\30\1\0\2\30\12\0\26\30\12\0\32\30\106\0\70\30"+
    "\6\0\2\30\100\0\1\30\3\31\1\0\2\31\5\0\4\31\4\30"+
    "\1\0\3\30\1\0\33\30\4\0\3\31\4\0\1\31\40\0\35\30"+
    "\3\0\35\30\43\0\10\30\1\0\34\30\2\31\31\0\66\30\12\0"+
    "\26\30\12\0\23\30\15\0\22\30\156\0\111\30\67\0\63\30\15\0"+
    "\63\30\u030d\0\3\31\65\30\17\31\37\0\12\31\17\0\4\31\55\30"+
    "\13\31\2\0\1\31\22\0\31\30\7\0\12\31\6\0\3\31\44\30"+
    "\16\31\1\0\12\31\20\0\43\30\1\31\2\0\1\30\11\0\3\31"+
    "\60\30\16\31\4\30\5\0\3\31\3\0\12\31\1\30\1\0\1\30"+
    "\43\0\22\30\1\0\31\30\14\31\6\0\1\31\101\0\7\30\1\0"+
    "\1\30\1\0\4\30\1\0\17\30\1\0\12\30\7\0\57\30\14\31"+
    "\5\0\12\31\6\0\4\31\1\0\10\30\2\0\2\30\2\0\26\30"+
    "\1\0\7\30\1\0\2\30\1\0\5\30\2\0\1\31\1\30\7\31"+
    "\2\0\2\31\2\0\3\31\2\0\1\30\6\0\1\31\5\0\5\30"+
    "\2\31\2\0\7\31\3\0\5\31\213\0\65\30\22\31\4\30\5\0"+
    "\12\31\46\0\60\30\24\31\2\30\1\0\1\30\10\0\12\31\246\0"+
    "\57\30\7\31\2\0\11\31\27\0\4\30\2\31\42\0\60\30\21\31"+
    "\3\0\1\30\13\0\12\31\46\0\53\30\15\31\10\0\12\31\66\0"+
    "\32\30\3\0\17\31\4\0\12\31\u0166\0\100\30\12\31\25\0\1\30"+
    "\u0100\0\1\30\12\31\50\30\7\31\1\30\4\31\10\0\1\31\10\0"+
    "\1\30\13\31\50\30\2\0\4\30\20\31\46\0\71\30\u0107\0\11\30"+
    "\1\0\45\30\10\31\1\0\10\31\1\30\17\0\12\31\30\0\36\30"+
    "\2\0\26\31\1\0\16\31\111\0\7\30\1\0\2\30\1\0\46\30"+
    "\6\31\3\0\1\31\1\0\2\31\1\0\7\31\1\30\1\31\10\0"+
    "\12\31\u02a6\0\u039a\30\146\0\157\30\21\0\304\30\u0abc\0\u042f\30\u0fd1\0"+
    "\u0247\30\u21b9\0\u0239\30\7\0\37\30\1\0\12\31\146\0\36\30\2\0"+
    "\5\31\13\0\60\30\7\31\11\0\4\30\14\0\12\31\11\0\25\30"+
    "\5\0\23\30\u0370\0\105\30\13\0\1\30\56\31\20\0\4\31\15\30"+
    "\100\0\2\30\36\0\u17ed\30\23\0\u02f3\30\u250d\0\u011f\30\121\0\u018c\30"+
    "\u0904\0\153\30\5\0\15\30\3\0\11\30\7\0\12\30\3\0\2\31"+
    "\1\0\4\31\u14c1\0\5\31\3\0\26\31\2\0\7\31\36\0\4\31"+
    "\224\0\3\31\u01bb\0\125\30\1\0\107\30\1\0\2\30\2\0\1\30"+
    "\2\0\2\30\2\0\4\30\1\0\14\30\1\0\1\30\1\0\7\30"+
    "\1\0\101\30\1\0\4\30\2\0\10\30\1\0\7\30\1\0\34\30"+
    "\1\0\4\30\1\0\5\30\1\0\1\30\3\0\7\30\1\0\u0154\30"+
    "\2\0\31\30\1\0\31\30\1\0\37\30\1\0\31\30\1\0\37\30"+
    "\1\0\31\30\1\0\37\30\1\0\31\30\1\0\37\30\1\0\31\30"+
    "\1\0\10\30\2\0\62\31\u0200\0\67\31\4\0\62\31\10\0\1\31"+
    "\16\0\1\31\26\0\5\31\1\0\17\31\u0550\0\7\31\1\0\21\31"+
    "\2\0\7\31\1\0\2\31\1\0\5\31\u07d5\0\305\30\13\0\7\31"+
    "\51\0\104\30\7\31\5\0\12\31\u04a6\0\4\30\1\0\33\30\1\0"+
    "\2\30\1\0\1\30\2\0\1\30\1\0\12\30\1\0\4\30\1\0"+
    "\1\30\1\0\1\30\6\0\1\30\4\0\1\30\1\0\1\30\1\0"+
    "\1\30\1\0\3\30\1\0\2\30\1\0\1\30\2\0\1\30\1\0"+
    "\1\30\1\0\1\30\1\0\1\30\1\0\1\30\1\0\2\30\1\0"+
    "\1\30\2\0\4\30\1\0\7\30\1\0\4\30\1\0\4\30\1\0"+
    "\1\30\1\0\12\30\1\0\21\30\5\0\3\30\1\0\5\30\1\0"+
    "\21\30\u1144\0\ua6d7\30\51\0\u1035\30\13\0\336\30\2\0\u1682\30\16\0"+
    "\u1d31\30\u0c1f\0\u021e\30\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\31\36\0\140\31\200\0\360\31\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\2\2\13\3\1\4\1\1\1\5\3\4"+
    "\1\6\1\7\1\10\1\1\2\11\3\1\1\12\1\13"+
    "\1\12\1\1\1\14\13\3\1\2\2\1\17\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\146\0\252\0\314"+
    "\0\356\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba\0\u01dc"+
    "\0\u01fe\0\u0220\0\u0242\0\146\0\146\0\u0264\0\u0286\0\146"+
    "\0\u02a8\0\146\0\u02ca\0\u02ec\0\u02ca\0\u030e\0\u0330\0\u0352"+
    "\0\u02ca\0\u0374\0\u0396\0\u03b8\0\356\0\u03da\0\u03fc\0\u041e"+
    "\0\u0440\0\u0462\0\u0484\0\u04a6\0\u04c8\0\u04ea\0\u050c\0\u052e"+
    "\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8\0\u05fa\0\u061c\0\u063e"+
    "\0\u0660\0\u0682\0\u06a4\0\u06c6\0\u06e8\0\u070a\0\u072c\0\u074e"+
    "\0\u0770\0\u0792";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\12\1\13"+
    "\2\11\1\14\1\11\1\15\1\16\1\11\1\17\1\20"+
    "\1\21\3\11\1\22\1\23\1\11\1\4\1\24\1\25"+
    "\2\26\1\27\1\11\1\30\1\4\1\31\2\4\35\31"+
    "\1\32\1\4\1\33\1\34\2\35\2\33\1\36\2\33"+
    "\1\37\5\33\1\40\6\33\1\41\3\33\1\42\1\41"+
    "\2\43\1\41\1\44\2\33\44\0\1\6\43\0\1\11"+
    "\1\45\1\46\17\11\2\0\3\11\4\0\1\11\6\0"+
    "\5\11\1\47\5\11\1\15\6\11\2\0\3\11\4\0"+
    "\1\11\6\0\22\11\2\0\3\11\4\0\1\11\6\0"+
    "\12\11\1\50\6\11\1\51\2\0\3\11\4\0\1\11"+
    "\6\0\5\11\1\52\14\11\2\0\3\11\4\0\1\11"+
    "\6\0\5\11\1\53\14\11\2\0\3\11\4\0\1\11"+
    "\6\0\10\11\1\54\11\11\2\0\3\11\4\0\1\11"+
    "\6\0\11\11\1\55\10\11\2\0\3\11\4\0\1\11"+
    "\6\0\3\11\1\56\16\11\2\0\3\11\4\0\1\11"+
    "\6\0\5\11\1\57\14\11\2\0\3\11\4\0\1\11"+
    "\6\0\12\11\1\60\7\11\2\0\3\11\4\0\1\11"+
    "\30\0\1\61\42\0\1\61\47\0\1\25\36\0\1\24"+
    "\7\0\1\31\2\0\35\31\2\0\32\33\1\0\11\33"+
    "\1\35\27\33\1\0\20\33\1\62\20\33\1\0\25\33"+
    "\1\41\13\33\1\0\15\33\1\63\23\33\1\0\7\33"+
    "\32\0\1\42\7\0\32\33\1\0\2\33\1\41\15\33"+
    "\1\63\20\33\1\0\7\33\4\0\3\11\1\45\16\11"+
    "\2\0\3\11\4\0\1\11\6\0\12\11\1\45\7\11"+
    "\2\0\3\11\4\0\1\11\6\0\6\11\1\64\13\11"+
    "\2\0\3\11\4\0\1\11\6\0\11\11\1\65\10\11"+
    "\2\0\3\11\4\0\1\11\6\0\6\11\1\66\13\11"+
    "\2\0\3\11\4\0\1\11\6\0\5\11\1\67\14\11"+
    "\2\0\3\11\4\0\1\11\6\0\14\11\1\64\5\11"+
    "\2\0\3\11\4\0\1\11\6\0\3\11\1\70\16\11"+
    "\2\0\3\11\4\0\1\11\6\0\12\11\1\71\7\11"+
    "\2\0\3\11\4\0\1\11\6\0\1\72\21\11\2\0"+
    "\3\11\4\0\1\11\6\0\1\73\21\11\2\0\3\11"+
    "\4\0\1\11\2\0\1\61\1\5\1\6\37\61\7\33"+
    "\1\41\22\33\1\0\17\33\1\41\21\33\1\0\7\33"+
    "\4\0\11\11\1\45\10\11\2\0\3\11\4\0\1\11"+
    "\6\0\2\11\1\45\17\11\2\0\3\11\4\0\1\11"+
    "\6\0\7\11\1\74\12\11\2\0\3\11\4\0\1\11"+
    "\6\0\10\11\1\45\11\11\2\0\3\11\4\0\1\11"+
    "\6\0\6\11\1\75\13\11\2\0\3\11\4\0\1\11"+
    "\6\0\1\76\5\11\1\77\13\11\2\0\3\11\4\0"+
    "\1\11\6\0\4\11\1\45\15\11\2\0\3\11\4\0"+
    "\1\11\6\0\2\11\1\100\17\11\2\0\3\11\4\0"+
    "\1\11\6\0\10\11\1\64\11\11\2\0\3\11\4\0"+
    "\1\11\6\0\12\11\1\65\7\11\2\0\3\11\4\0"+
    "\1\11\6\0\2\11\1\101\17\11\2\0\3\11\4\0"+
    "\1\11\6\0\20\11\1\46\1\11\2\0\3\11\4\0"+
    "\1\11\6\0\3\11\1\102\16\11\2\0\3\11\4\0"+
    "\1\11\6\0\17\11\1\45\2\11\2\0\3\11\4\0"+
    "\1\11\6\0\1\11\1\45\20\11\2\0\3\11\4\0"+
    "\1\11\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1972];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\1\1\1\11\15\1\2\11\2\1"+
    "\1\11\1\1\1\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
StringBuilder sb = new StringBuilder();
String op = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3426) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  private static String zzToPrintable(String str) {
    StringBuilder builder = new StringBuilder();
    for (int n = 0 ; n < str.length() ; ) {
      int ch = str.codePointAt(n);
      int charCount = Character.charCount(ch);
      n += charCount;
      if (ch > 31 && ch < 127) {
        builder.append((char)ch);
      } else if (charCount == 1) {
        builder.append(String.format("\\u%04X", ch));
      } else {
        builder.append(String.format("\\U%06X", ch));
      }
    }
    return builder.toString();
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING: {
              System.out.println("match: <<EOF>>");
              System.out.println("action [104] { throw new Error(\"Illegal character <\"+"+ZZ_NL+"                                                yytext()+\">\"); }");
              throw new Error("Illegal character <"+
                                                yytext()+">");
            }  // fall though
            case 67: break;
            case INTEGER: {
              System.out.println("match: <<EOF>>");
              System.out.println("action [64] { yybegin(YYINITIAL);"+ZZ_NL+"                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else{return new Yytoken(SymbolTable.INTEGER,sb.toString());} }");
              yybegin(YYINITIAL);
                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else{return new Yytoken(SymbolTable.INTEGER,sb.toString());}
            }  // fall though
            case 68: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [87] { throw new Error(\"Illegal character <\"+"+ZZ_NL+"                                                yytext()+\">\"); }");
            { throw new Error("Illegal character <"+
                                                yytext()+">");
            } 
            // fall through
          case 13: break;
          case 2: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [45] { /* ignore */ }");
            { /* ignore */
            } 
            // fall through
          case 14: break;
          case 3: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [35] { return new Yytoken(SymbolTable.IDENTIFIER,yytext()); }");
            { return new Yytoken(SymbolTable.IDENTIFIER,yytext());
            } 
            // fall through
          case 15: break;
          case 4: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [47] { return new Yytoken(SymbolTable.SYMBOL,yytext()); }");
            { return new Yytoken(SymbolTable.SYMBOL,yytext());
            } 
            // fall through
          case 16: break;
          case 5: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [49] { sb.setLength(0); sb.append(yytext());yybegin(INTEGER); }");
            { sb.setLength(0); sb.append(yytext());yybegin(INTEGER);
            } 
            // fall through
          case 17: break;
          case 6: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [39] { sb.setLength(0); yybegin(STRING); }");
            { sb.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 18: break;
          case 7: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [106] { sb.append( yytext() ); }");
            { sb.append( yytext() );
            } 
            // fall through
          case 19: break;
          case 8: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [101] { yybegin(YYINITIAL);"+ZZ_NL+"                               return new Yytoken(SymbolTable.STRING_LITERAL,"+ZZ_NL+"                               sb.toString()); }");
            { yybegin(YYINITIAL);
                               return new Yytoken(SymbolTable.STRING_LITERAL,
                               sb.toString());
            } 
            // fall through
          case 20: break;
          case 9: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [53] { yybegin(YYINITIAL);"+ZZ_NL+"                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else{return new Yytoken(SymbolTable.INTEGER,sb.toString());} }");
            { yybegin(YYINITIAL);
                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else{return new Yytoken(SymbolTable.INTEGER,sb.toString());}
            } 
            // fall through
          case 21: break;
          case 10: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [74] { yybegin(YYINITIAL);"+ZZ_NL+"                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else{"+ZZ_NL+"                                    return new Yytoken(SymbolTable.INTEGER,sb.toString());} }");
            { yybegin(YYINITIAL);
                                if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else{
                                    return new Yytoken(SymbolTable.INTEGER,sb.toString());}
            } 
            // fall through
          case 22: break;
          case 11: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [89] { yybegin(YYINITIAL);sb.append(yytext());"+ZZ_NL+"                            if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){"+ZZ_NL+"                                    throw new Error(\"Integer out of bound <\"+"+ZZ_NL+"                                                yytext()+\">\");}"+ZZ_NL+"                                else{"+ZZ_NL+"                                    return new Yytoken(SymbolTable.INTEGER,sb.toString());} }");
            { yybegin(YYINITIAL);sb.append(yytext());
                            if(Integer.parseInt(sb.toString())>Integer.MAX_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else if(Integer.parseInt(sb.toString())<Integer.MIN_VALUE){
                                    throw new Error("Integer out of bound <"+
                                                yytext()+">");}
                                else{
                                    return new Yytoken(SymbolTable.INTEGER,sb.toString());}
            } 
            // fall through
          case 23: break;
          case 12: 
            System.out.println("match: --"+zzToPrintable(yytext())+"--");
            System.out.println("action [33] { return new Yytoken(SymbolTable.RESERVE_WORD,yytext()); }");
            { return new Yytoken(SymbolTable.RESERVE_WORD,yytext());
            } 
            // fall through
          case 24: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          do {
            System.out.println(scanner.yylex());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
